# Generated by Django 5.2.4 on 2025-07-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('client_code', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('login_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('has_branches', models.BooleanField(default=False)),
                ('strength', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
