# Generated by Django 5.2.4 on 2025-07-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('reported_by', models.CharField(max_length=255)),
                ('responded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], max_length=20)),
                ('time_taken', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('solved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
