# Generated by Django 5.2.4 on 2025-07-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_supportcall_alter_client_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcall',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supportcall',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supportcall',
            name='reported_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supportcall',
            name='responded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportcall',
            name='solved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportcall',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='supportcall',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supportcall',
            name='time_taken',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
