# Generated by Django 5.2.4 on 2025-07-12 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_alter_supportcall_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('paid_on', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_to', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.client')),
            ],
        ),
    ]
