# Generated by Django 5.2.4 on 2025-07-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_allpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpayments',
            name='transaction_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allpayments',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allpayments',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
    ]
