# Generated by Django 5.2.4 on 2025-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='weblink',
            field=models.URLField(blank=True),
        ),
    ]
