# Generated by Django 5.2.4 on 2025-07-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_appuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='AllUsers',
        ),
    ]
