# Generated by Django 5.2.4 on 2025-07-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_rename_appuser_allusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
