# Generated by Django 5.2.4 on 2025-07-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0010_alter_branch_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='password',
        ),
    ]
