# Generated by Django 5.2.4 on 2025-07-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0011_remove_branch_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='strength',
            field=models.IntegerField(default=0, null=0),
            preserve_default=False,
        ),
    ]
