# Generated by Django 5.2.4 on 2025-07-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0012_alter_client_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='additional_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
