# Generated by Django 5.2.4 on 2025-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0013_branch_additional_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='additional_link',
        ),
        migrations.AddField(
            model_name='client',
            name='additional_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
