# Generated by Django 5.2.4 on 2025-07-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0014_remove_branch_additional_link_client_additional_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcall',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.client'),
        ),
    ]
