# Generated by Django 5.2.4 on 2025-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0015_alter_supportcall_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='additional_link',
        ),
        migrations.AlterField(
            model_name='supportcall',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
    ]
