# Generated by Django 5.2.4 on 2025-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0016_remove_client_additional_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='additional_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
