# Generated by Django 5.2.4 on 2025-07-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0017_client_additional_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='strength',
            field=models.IntegerField(null=True),
        ),
    ]
