# Generated by Django 5.2.4 on 2025-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0018_alter_client_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='strength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
