# Generated by Django 5.2.4 on 2025-07-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0019_alter_client_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='strength',
            field=models.IntegerField(blank=0, default=0, null=0),
            preserve_default=False,
        ),
    ]
