# Generated by Django 5.2.4 on 2025-07-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0021_alter_client_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcall',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
